pe.com.cibereletrik/Controllers/MarcaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pe.com.cibereletrik;

namespace pe.com.cibereletrik.Controllers
{
    public class MarcaController : Controller
    {
        private bdciberelectrik2026Entities db = new bdciberelectrik2026Entities();

        // GET: Marca
        public ActionResult Index()
        {
            var lista = db.Database.SqlQuery<marca>("SP_MostrarMarcaTodo").ToList();
            return View(lista);
        }

        // GET: Marca/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SqlParameter pid = new SqlParameter("@codigo", id);
            var marca = db.Database.SqlQuery<marca>
                ("SP_BuscarMarcaXCodigo @codigo", pid).FirstOrDefault();
            if (marca == null)
            {
                return HttpNotFound();
            }
            return View(marca);
        }

        // GET: Marca/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Marca/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "codmar,nommar,estmar")] marca marca)
        {
            if (ModelState.IsValid)
            {
                db.Database.ExecuteSqlCommand(
                    "SP_RegistrarMarca @nombre, @estado",
                    new SqlParameter("@nombre", marca.nommar),
                    new SqlParameter("@estado", marca.estmar)
                    );
                return RedirectToAction("Index");
            }

            return View(marca);
        }

        // GET: Marca/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SqlParameter pid = new SqlParameter("@codigo", id);
            var marca = db.Database.SqlQuery<marca>
                ("SP_BuscarMarcaXCodigo @codigo", pid).FirstOrDefault();
            if (marca == null)
            {
                return HttpNotFound();
            }
            return View(marca);
        }

        // POST: Marca/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "codmar,nommar,estmar")] marca marca)
        {
            if (ModelState.IsValid)
            {
                db.Database.ExecuteSqlCommand(
                    "SP_ActualizarMarca @codigo,@nombre, @estado",
                    new SqlParameter("@codigo", marca.codmar),
                    new SqlParameter("@nombre", marca.nommar),
                    new SqlParameter("@estado", marca.estmar)
                    );
                return RedirectToAction("Index");
            }
            return View(marca);
        }

        // GET: Marca/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SqlParameter pid = new SqlParameter("@codigo", id);
            var marca = db.Database.SqlQuery<marca>
                ("SP_BuscarMarcaXCodigo @codigo", pid).FirstOrDefault();
            if (marca == null)
            {
                return HttpNotFound();
            }
            return View(marca);
        }

        // POST: Marca/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.Database.ExecuteSqlCommand(
                "SP_EliminarMarca @codigo",
                new SqlParameter("@codigo", id)
                );
            return RedirectToAction("Index");
        }


        // GET: Marca/Enable/5
        public ActionResult Enable(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SqlParameter pid = new SqlParameter("@codigo", id);
            var marca = db.Database.SqlQuery<marca>
                ("SP_BuscarMarcaXCodigo @codigo", pid).FirstOrDefault();
            if (marca == null)
            {
                return HttpNotFound();
            }
            return View(marca);
        }

        // POST: Marca/Enable/5
        [HttpPost, ActionName("Enable")]
        [ValidateAntiForgeryToken]
        public ActionResult EnableConfirmed(int id)
        {
            db.Database.ExecuteSqlCommand(
                "SP_HabilitarMarca @codigo",
                new SqlParameter("@codigo", id)
                );
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pe.com.cibereletrik/Controllers/RolController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pe.com.cibereletrik;

namespace pe.com.cibereletrik.Controllers
{
    public class RolController : Controller
    {
        private bdciberelectrik2026Entities db = new bdciberelectrik2026Entities();

        // GET: Rol
        public ActionResult Index()
        {
            var lista = db.Database.SqlQuery<rol>("SP_MostrarRolTodo").ToList();
            return View(lista);
        }

        // GET: Rol/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var codigo = new SqlParameter("@codigo", id);
            rol rol = db.Database.SqlQuery<rol>("SP_BuscarRolXCodigo @codigo", codigo).FirstOrDefault();
            if (rol == null)
            {
                return HttpNotFound();
            }
            return View(rol);
        }

        // GET: Rol/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rol/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "codrol,nomrol,estrol")] rol rol)
        {
            if (ModelState.IsValid)
            {
                var nombre = new SqlParameter("@nombre", rol.nomrol);
                var estado = new SqlParameter("@estado", rol.estrol);
                db.Database.ExecuteSqlCommand("SP_RegistrarRol @nombre, @estado", nombre, estado);
                return RedirectToAction("Index");
            }

            return View(rol);
        }

        // GET: Rol/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var codigo = new SqlParameter("@codigo", id);
            rol rol = db.Database.SqlQuery<rol>("SP_BuscarRolXCodigo @codigo", codigo).FirstOrDefault();
            if (rol == null)
            {
                return HttpNotFound();
            }
            return View(rol);
        }

        // POST: Rol/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "codrol,nomrol,estrol")] rol rol)
        {
            if (ModelState.IsValid)
            {
                var codigo = new SqlParameter("@codigo", rol.codrol);
                var nombre = new SqlParameter("@nombre", rol.nomrol);
                var estado = new SqlParameter("@estado", rol.estrol);
                db.Database.ExecuteSqlCommand("SP_ActualizarRol @codigo, @nombre, @estado", codigo, nombre, estado);
                return RedirectToAction("Index");
            }
            return View(rol);
        }

        // GET: Rol/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var codigo = new SqlParameter("@codigo", id);
            rol rol = db.Database.SqlQuery<rol>("SP_BuscarRolXCodigo @codigo", codigo).FirstOrDefault();
            if (rol == null)
            {
                return HttpNotFound();
            }
            return View(rol);
        }

        // POST: Rol/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var codigo = new SqlParameter("@codigo", id);
            db.Database.ExecuteSqlCommand("SP_EliminarRol @codigo", codigo);
            return RedirectToAction("Index");
        }

        // GET: Rol/Enable/5
        public ActionResult Enable(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var codigo = new SqlParameter("@codigo", id);
            rol rol = db.Database.SqlQuery<rol>("SP_BuscarRolXCodigo @codigo", codigo).FirstOrDefault();
            if (rol == null)
            {
                return HttpNotFound();
            }
            return View(rol);
        }

        // POST: Rol/Enable/5
        [HttpPost, ActionName("Enable")]
        [ValidateAntiForgeryToken]
        public ActionResult EnableConfirmed(int id)
        {
            var codigo = new SqlParameter("@codigo", id);
            db.Database.ExecuteSqlCommand("SP_HabilitarRol @codigo", codigo);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pe.com.cibereletrik/Controllers/SexoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pe.com.cibereletrik;

namespace pe.com.cibereletrik.Controllers
{
    public class SexoController : Controller
    {
        private bdciberelectrik2026Entities db = new bdciberelectrik2026Entities();

        // GET: Sexo
        public ActionResult Index()
        {
            var lista = db.Database.SqlQuery<sexo>("SP_MostrarSexoTodo").ToList();
            return View(lista);
        }

        // GET: Sexo/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var codigo = new SqlParameter("@codigo", id);
            sexo sexo = db.Database.SqlQuery<sexo>("SP_BuscarSexoXCodigo @codigo", codigo).FirstOrDefault();
            if (sexo == null)
            {
                return HttpNotFound();
            }
            return View(sexo);
        }

        // GET: Sexo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sexo/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "codsex,nomsex,estsex")] sexo sexo)
        {
            if (ModelState.IsValid)
            {
                var nombre = new SqlParameter("@nombre", sexo.nomsex);
                var estado = new SqlParameter("@estado", sexo.estsex);
                db.Database.ExecuteSqlCommand("SP_RegistrarSexo @nombre, @estado", nombre, estado);
                return RedirectToAction("Index");
            }

            return View(sexo);
        }

        // GET: Sexo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var codigo = new SqlParameter("@codigo", id);
            sexo sexo = db.Database.SqlQuery<sexo>("SP_BuscarSexoXCodigo @codigo", codigo).FirstOrDefault();
            if (sexo == null)
            {
                return HttpNotFound();
            }
            return View(sexo);
        }

        // POST: Sexo/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "codsex,nomsex,estsex")] sexo sexo)
        {
            if (ModelState.IsValid)
            {
                var codigo = new SqlParameter("@codigo", sexo.codsex);
                var nombre = new SqlParameter("@nombre", sexo.nomsex);
                var estado = new SqlParameter("@estado", sexo.estsex);
                db.Database.ExecuteSqlCommand("SP_ActualizarSexo @codigo, @nombre, @estado", codigo, nombre, estado);
                return RedirectToAction("Index");
            }
            return View(sexo);
        }

        // GET: Sexo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var codigo = new SqlParameter("@codigo", id);
            sexo sexo = db.Database.SqlQuery<sexo>("SP_BuscarSexoXCodigo @codigo", codigo).FirstOrDefault();
            if (sexo == null)
            {
                return HttpNotFound();
            }
            return View(sexo);
        }

        // POST: Sexo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var codigo = new SqlParameter("@codigo", id);
            db.Database.ExecuteSqlCommand("SP_EliminarSexo @codigo", codigo);
            return RedirectToAction("Index");
        }

        // GET: Sexo/Enable/5
        public ActionResult Enable(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var codigo = new SqlParameter("@codigo", id);
            sexo sexo = db.Database.SqlQuery<sexo>("SP_BuscarSexoXCodigo @codigo", codigo).FirstOrDefault();
            if (sexo == null)
            {
                return HttpNotFound();
            }
            return View(sexo);
        }

        // POST: Sexo/Enable/5
        [HttpPost, ActionName("Enable")]
        [ValidateAntiForgeryToken]
        public ActionResult EnableConfirmed(int id)
        {
            var codigo = new SqlParameter("@codigo", id);
            db.Database.ExecuteSqlCommand("SP_HabilitarSexo @codigo", codigo);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pe.com.cibereletrik/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CiberElectrik</title>
    @*<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    @*<script src="~/Scripts/modernizr-2.6.2.js"></script>*@
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        footer {
            background-color: #212529;
            color: #FFFFF2;
            text-align: center;
            justify-content: center;
            padding: 15px,0;
            width: 100%;
            position: relative;
            bottom: 0;
        }

        .body-content {
            flex: 1;
        }

        /* Estilos para las tablas */
        .table {
            background-color: white;
            border-radius: 8px;
            overflow: hidden;
        }

        .table thead th {
            background-color: #212529;
            color: white;
            border: none;
            padding: 12px;
            font-weight: 600;
        }

        .table tbody td {
            padding: 12px;
            vertical-align: middle;
        }

        /* Botones de acción */
        .btn-actualizar {
            background-color: #198754;
            color: white;
            border: none;
            padding: 8px 20px;
            border-radius: 4px;
            font-weight: 500;
            transition: background-color 0.3s;
        }

        .btn-actualizar:hover {
            background-color: #157347;
            color: white;
        }

        .btn-detalles {
            background-color: #6c757d;
            color: white;
            border: none;
            padding: 8px 20px;
            border-radius: 4px;
            font-weight: 500;
            transition: background-color 0.3s;
        }

        .btn-detalles:hover {
            background-color: #5c636a;
            color: white;
        }

        .btn-eliminar {
            background-color: #dc3545;
            color: white;
            border: none;
            padding: 8px 20px;
            border-radius: 4px;
            font-weight: 500;
            transition: background-color 0.3s;
        }

        .btn-eliminar:hover {
            background-color: #bb2d3b;
            color: white;
        }

        .btn-habilitar {
            background-color: #ffc107;
            color: #212529;
            border: none;
            padding: 8px 20px;
            border-radius: 4px;
            font-weight: 500;
            transition: background-color 0.3s;
        }

        .btn-habilitar:hover {
            background-color: #ffca2c;
            color: #212529;
        }

        /* Estado Habilitado/Deshabilitado */
        .badge-habilitado {
            background-color: #198754;
            color: white;
            padding: 6px 12px;
            border-radius: 4px;
            font-weight: 500;
        }

        .badge-deshabilitado {
            background-color: #dc3545;
            color: white;
            padding: 6px 12px;
            border-radius: 4px;
            font-weight: 500;
        }

        /* Botón Nuevo */
        .btn-nuevo {
            background-color: #0d6efd;
            color: white;
            border: none;
            padding: 10px 24px;
            border-radius: 4px;
            font-weight: 500;
            margin-bottom: 20px;
        }

        .btn-nuevo:hover {
            background-color: #0b5ed7;
            color: white;
        }
    </style>
</head>
<body>
    <nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">CiberElectrik</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Home")">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Quienes Somos</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Mantenimiento Simple
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="@Url.Action("Index", "Marca")">Marca</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("Index", "Categoria")">Categoria</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("Index", "Distrito")">Distrito</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("Index", "Rol")">Rol</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("Index", "TipoDocumento")">Tipo de Documento</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("Index", "Sexo")">Sexo</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Mantenimiento Doble
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="@Url.Action("Index", "Producto")">Producto</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("Index", "Cliente")">Cliente</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("Index", "Empleado")">Empleado</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </div>
        </div>*@

    <div class="container body-content">
        @RenderBody()
    </div>
    <footer>
        <p>&copy; @DateTime.Now.Year - CiberElectrik</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    @*<script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>*@
</body>
</html>

pe.com.cibereletrik/Views/Shared/_LoginLayout.cshtml
<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - CiberElectrik</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <style>
        body {
            background: linear-gradient(to bottom,#7431F9,#000000);
        }
    </style>
</head>
<body>
    <div class="container">
        @RenderBody()
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
</html>